bindings:
  category:
    name: "Saswave Amazon Product Scraper (Category)"
    actor_id: "saswave/amazon-product-scraper"
    task_id: ""
    input_adapter: "saswave_category"
    amazon_domain: "www.amazon.com"
    build: "latest"
    memory_mbytes: 4096
  competitor:
    name: "Saswave Amazon Product Scraper (Competitor)"
    actor_id: "saswave/amazon-product-scraper"
    task_id: ""
    input_adapter: "saswave_competitor"
    amazon_domain: "www.amazon.com"
    build: "latest"
    memory_mbytes: 4096
